version: 2
updates:
  - package-ecosystem: maven
    directories:
      - /
      - /library-api
    schedule:
      interval: weekly
    groups:
      spring-boot:
        patterns:
          - org.springframework.boot:*
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
