spring.jpa.open-in-view=false
library.circulation.loan-days=14
library.circulation.renewal-days=14
library.circulation.max-renewals=2
library.circulation.max-active-loans=5
library.circulation.time-zone=UTC

library.api.version=@project.version@
springdoc.paths-to-match=/api/**
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.default-produces-media-type=application/json
springdoc.override-with-generic-response=false
